apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: no-storage
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  backup:
    enabled: false
    storages:
    tasks:
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 1
      slowOpThresholdMs: 100
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
  replsets:
  - name: rs0
    resources:
      limits:
        cpu: 600m
        memory: 1G
      requests:
        cpu: 600m
        memory: 1G
    size: 3
  secrets:
    key: some-key
    users: some-users
    ssl: some-name-ssl
