apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name: restore1
spec:
  clusterName: my-cluster-name
  backupName: backup1
#  pitr:
#    type: date
#    date: YYYY-MM-DD HH:MM:SS
